a=int(input("Enter a: "));
b=int(input("Enter b: "));
print("[Before Swapping][using BITWISE]");
print("a: ",a);
print("b: ",b);
a=a^b;
b=a^b;
a=a^b;
print("[After Swapping][using BITWISE]");
print("a: ",a);
print("b: ",b);
