a=int(input("Enter a: "));
b=int(input("Enter b: "));
print("[Before Swapping][without using 3rd Variable]");
print("a: ",a);
print("b: ",b);
a=a+b;
b=a-b;
a=a-b;
print("[After Swapping][without using 3rd Variable]");
print("a: ",a);
print("b: ",b);
